PEOPLE_SERVER_IP = "0.0.0.0"
PEOPLE_SERVER_PORT = "5000"
COVID_TRACKER_SERVER_IP = "127.0.0.1"
COVID_TRACKER_SERVER_PORT = "3000"

BASE_URI = f"http://{PEOPLE_SERVER_IP}:{PEOPLE_SERVER_PORT}/api/people"
COVID_TRACKER_HOST = f"http://{COVID_TRACKER_SERVER_IP}:{COVID_TRACKER_SERVER_PORT}"
